### PR TITLE
A few updates

### PR DESCRIPTION
**Pull request by kylon**

### CODE REVIEW

**Comment by kylon** [comment]
L and R are not available because they are ignored by lolicon for some reason

[spoiler: i'm planning a 2nd code cleanup]

**Comment by dots-tb** [comment]
Removing features is a no-no

**Comment by kylon** [comment]
the whole pr?
anyway commits are reversible, but ok :\

**Comment by dots-tb** [comment]
Sorry, I'm not trying to be a downer but but they do not fall in line with the project.

The exit game is a very important feature as reloading a game as normally you'd have to: press home, swipe, find the icon again, click it twice. But this was removed as the shell_pid check was removed in order to remedy the controls issue I think?

Customization will never be in LOLIcon.

I will rewrite the LOLIcon at a later date as I did with rePatch.  I do admit its not well written and was rushed out to be released while I still had time. The whole oClock profile system will be removed. 

However, I do enjoy your interest in the project, will support your branch, and users may use your build as an alternative. 

Hope you understand. Thanks.

**Comment by kylon** [comment]
np

your plugins are amazing, and LOLIcon is the only way i have to play some games at a decent framerate (eg Helldivers, default is 15pfs when too many mobs are on screen....)

i think a way to customize buttons is needed becuase select and up is not good for all the games (also on phat, the select button is uncomfortable due to its size)

i will revert that commit and add builds on my repo then.


just a few notes:

somehow is still possible to open LOLIcon in pspemu|adrenaline but it is not drawn in pspemu fb (i was able to see it only once, dunno how) and you can't close it so you are stuck because controls are not working (any of them).
your only option is to hard reset the device.
i tried to fix this in my last commit and it seems i can't reproduce the problem now (but not sure).


Thanks, looking forward the next LOLIcon version

**Pull request closed without merging**
